version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites:/etc/nginx/sites-enabled
      - ./logs:/var/log/nginx
    restart: always
    networks:
      - aa_network

networks:
  aa_network:
    driver: bridge

include:
  - ./projects/jobmosaic/docker-compose.yml
