version: "3"

services:
  temp_nginx:
    image: nginx:latest
    ports:
    - 80:80
    - 443:443
    volumes:
    - /etc/letsencrypt:/etc/letsencrypt:ro
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./html:/usr/share/nginx/html
      #- ./sites:/etc/nginx/sites-enabled
    restart: always
    networks:
      - delete_me_network

  temp_nginx2:
    image: nginx:latest
    ports:
      - "80"
      # - 3000:80
      # - 3001:443
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./html2:/usr/share/nginx/html
        #- ./sites:/etc/nginx/sites-enabled
    restart: always
    networks:
      - delete_me_network

networks:
  delete_me_network:
    driver: bridge
